import { Bricolage_Grotesque, Plus_Jakarta_Sans } from 'next/font/google';
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Import Google fonts from next/font/google
const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  weight: ['200', '400', '800'],
  variable: '--font-bricolage', // Optional: Custom variable for Tailwind integration
});

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['200', '400', '800'],
  variable: '--font-jakarta', // Optional: Custom variable for Tailwind integration
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bricolage.variable} ${jakartaSans.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
